### PR TITLE
KM-9 [FE] Integrate productivity data into show profile component

### PR DESCRIPTION
**Pull request by JakeLuong**
Show productivity of specific user including:

1. Work log
2. Productivity
3. Done
4. Total of tickets
5. Estimated
6. Carried over

### CODE REVIEW

**Comment by TShida951** [comment]
Got error 

Did you test with latest backend codes?

スクリーンショット 2019-12-16 10 54 52

**Review by bataimx — APPROVED** [review]

**Comment by TShida951** [comment]
Fix warning please 

```
webpackHotDevClient.js:120 ./src/pages/User/ShowProfile.js
  Line 27:6:  React Hook useEffect has missing dependencies: 'dispatchProductive', 'id', and 'userProductiveData'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
```

**Comment by TShida951** [comment]
Thuan sprint id 25 shows error

**Comment by TShida951** [comment]
See also 

```
index.js:1375 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Chart (at ProductiveChart.js:50)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at ProductiveChart.js:49)
    in ChartRender (at ProductiveChart.js:76)

```

**Comment by bataimx** [comment]
> Thuan sprint id 25 shows error

@TShida951 this error will improve on KM-11, that i'll use Reducer to controll data to avoid missing data attributes.

> See also
> 
> ```
>     in Chart (at ProductiveChart.js:50)
>     in div (created by Styled(MuiBox))
>     in Styled(MuiBox) (at ProductiveChart.js:49)
>     in ChartRender (at ProductiveChart.js:76)
> ```

This will fix on KM-11 too

**Review by TShida951 — APPROVED** [review]

**Pull request merged**
